package cn.yurihentai.bean;

import java.io.Serializable;
import java.util.Date;

public class 权限 implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 权限表.编号
     *
     * @mbg.generated
     */
    private Long 编号;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 权限表.名称
     *
     * @mbg.generated
     */
    private String 名称;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 权限表.编码
     *
     * @mbg.generated
     */
    private String 编码;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 权限表.创建时间
     *
     * @mbg.generated
     */
    private Date 创建时间;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 权限表.修改时间
     *
     * @mbg.generated
     */
    private Date 修改时间;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 权限表.是否删除
     *
     * @mbg.generated
     */
    private Boolean 是否删除;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 权限表
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 权限表.编号
     *
     * @return the value of 权限表.编号
     *
     * @mbg.generated
     */
    public Long get编号() {
        return 编号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 权限表.编号
     *
     * @param 编号 the value for 权限表.编号
     *
     * @mbg.generated
     */
    public void set编号(Long 编号) {
        this.编号 = 编号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 权限表.名称
     *
     * @return the value of 权限表.名称
     *
     * @mbg.generated
     */
    public String get名称() {
        return 名称;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 权限表.名称
     *
     * @param 名称 the value for 权限表.名称
     *
     * @mbg.generated
     */
    public void set名称(String 名称) {
        this.名称 = 名称 == null ? null : 名称.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 权限表.编码
     *
     * @return the value of 权限表.编码
     *
     * @mbg.generated
     */
    public String get编码() {
        return 编码;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 权限表.编码
     *
     * @param 编码 the value for 权限表.编码
     *
     * @mbg.generated
     */
    public void set编码(String 编码) {
        this.编码 = 编码 == null ? null : 编码.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 权限表.创建时间
     *
     * @return the value of 权限表.创建时间
     *
     * @mbg.generated
     */
    public Date get创建时间() {
        return 创建时间;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 权限表.创建时间
     *
     * @param 创建时间 the value for 权限表.创建时间
     *
     * @mbg.generated
     */
    public void set创建时间(Date 创建时间) {
        this.创建时间 = 创建时间;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 权限表.修改时间
     *
     * @return the value of 权限表.修改时间
     *
     * @mbg.generated
     */
    public Date get修改时间() {
        return 修改时间;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 权限表.修改时间
     *
     * @param 修改时间 the value for 权限表.修改时间
     *
     * @mbg.generated
     */
    public void set修改时间(Date 修改时间) {
        this.修改时间 = 修改时间;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 权限表.是否删除
     *
     * @return the value of 权限表.是否删除
     *
     * @mbg.generated
     */
    public Boolean get是否删除() {
        return 是否删除;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 权限表.是否删除
     *
     * @param 是否删除 the value for 权限表.是否删除
     *
     * @mbg.generated
     */
    public void set是否删除(Boolean 是否删除) {
        this.是否删除 = 是否删除;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 权限表
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        权限 other = (权限) that;
        return (this.get编号() == null ? other.get编号() == null : this.get编号().equals(other.get编号()))
            && (this.get名称() == null ? other.get名称() == null : this.get名称().equals(other.get名称()))
            && (this.get编码() == null ? other.get编码() == null : this.get编码().equals(other.get编码()))
            && (this.get创建时间() == null ? other.get创建时间() == null : this.get创建时间().equals(other.get创建时间()))
            && (this.get修改时间() == null ? other.get修改时间() == null : this.get修改时间().equals(other.get修改时间()))
            && (this.get是否删除() == null ? other.get是否删除() == null : this.get是否删除().equals(other.get是否删除()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 权限表
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((get编号() == null) ? 0 : get编号().hashCode());
        result = prime * result + ((get名称() == null) ? 0 : get名称().hashCode());
        result = prime * result + ((get编码() == null) ? 0 : get编码().hashCode());
        result = prime * result + ((get创建时间() == null) ? 0 : get创建时间().hashCode());
        result = prime * result + ((get修改时间() == null) ? 0 : get修改时间().hashCode());
        result = prime * result + ((get是否删除() == null) ? 0 : get是否删除().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 权限表
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", 编号=").append(编号);
        sb.append(", 名称=").append(名称);
        sb.append(", 编码=").append(编码);
        sb.append(", 创建时间=").append(创建时间);
        sb.append(", 修改时间=").append(修改时间);
        sb.append(", 是否删除=").append(是否删除);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}