package xyz.yurihentai.bean;

import java.io.Serializable;
import java.util.Date;

public class 用户信息 implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 用户信息表.编号
     *
     * @mbg.generated
     */
    private Long 编号;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 用户信息表.姓名
     *
     * @mbg.generated
     */
    private String 姓名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 用户信息表.性别
     *
     * @mbg.generated
     */
    private Boolean 性别;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 用户信息表.年龄
     *
     * @mbg.generated
     */
    private Integer 年龄;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 用户信息表.生日
     *
     * @mbg.generated
     */
    private Date 生日;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 用户信息表.身份证号
     *
     * @mbg.generated
     */
    private String 身份证号;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 用户信息表.创建时间
     *
     * @mbg.generated
     */
    private Date 创建时间;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 用户信息表.修改时间
     *
     * @mbg.generated
     */
    private Date 修改时间;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 用户信息表.是否删除
     *
     * @mbg.generated
     */
    private Boolean 是否删除;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 用户信息表
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 用户信息表.编号
     *
     * @return the value of 用户信息表.编号
     *
     * @mbg.generated
     */
    public Long get编号() {
        return 编号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 用户信息表.编号
     *
     * @param 编号 the value for 用户信息表.编号
     *
     * @mbg.generated
     */
    public void set编号(Long 编号) {
        this.编号 = 编号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 用户信息表.姓名
     *
     * @return the value of 用户信息表.姓名
     *
     * @mbg.generated
     */
    public String get姓名() {
        return 姓名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 用户信息表.姓名
     *
     * @param 姓名 the value for 用户信息表.姓名
     *
     * @mbg.generated
     */
    public void set姓名(String 姓名) {
        this.姓名 = 姓名 == null ? null : 姓名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 用户信息表.性别
     *
     * @return the value of 用户信息表.性别
     *
     * @mbg.generated
     */
    public Boolean get性别() {
        return 性别;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 用户信息表.性别
     *
     * @param 性别 the value for 用户信息表.性别
     *
     * @mbg.generated
     */
    public void set性别(Boolean 性别) {
        this.性别 = 性别;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 用户信息表.年龄
     *
     * @return the value of 用户信息表.年龄
     *
     * @mbg.generated
     */
    public Integer get年龄() {
        return 年龄;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 用户信息表.年龄
     *
     * @param 年龄 the value for 用户信息表.年龄
     *
     * @mbg.generated
     */
    public void set年龄(Integer 年龄) {
        this.年龄 = 年龄;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 用户信息表.生日
     *
     * @return the value of 用户信息表.生日
     *
     * @mbg.generated
     */
    public Date get生日() {
        return 生日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 用户信息表.生日
     *
     * @param 生日 the value for 用户信息表.生日
     *
     * @mbg.generated
     */
    public void set生日(Date 生日) {
        this.生日 = 生日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 用户信息表.身份证号
     *
     * @return the value of 用户信息表.身份证号
     *
     * @mbg.generated
     */
    public String get身份证号() {
        return 身份证号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 用户信息表.身份证号
     *
     * @param 身份证号 the value for 用户信息表.身份证号
     *
     * @mbg.generated
     */
    public void set身份证号(String 身份证号) {
        this.身份证号 = 身份证号 == null ? null : 身份证号.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 用户信息表.创建时间
     *
     * @return the value of 用户信息表.创建时间
     *
     * @mbg.generated
     */
    public Date get创建时间() {
        return 创建时间;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 用户信息表.创建时间
     *
     * @param 创建时间 the value for 用户信息表.创建时间
     *
     * @mbg.generated
     */
    public void set创建时间(Date 创建时间) {
        this.创建时间 = 创建时间;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 用户信息表.修改时间
     *
     * @return the value of 用户信息表.修改时间
     *
     * @mbg.generated
     */
    public Date get修改时间() {
        return 修改时间;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 用户信息表.修改时间
     *
     * @param 修改时间 the value for 用户信息表.修改时间
     *
     * @mbg.generated
     */
    public void set修改时间(Date 修改时间) {
        this.修改时间 = 修改时间;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 用户信息表.是否删除
     *
     * @return the value of 用户信息表.是否删除
     *
     * @mbg.generated
     */
    public Boolean get是否删除() {
        return 是否删除;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 用户信息表.是否删除
     *
     * @param 是否删除 the value for 用户信息表.是否删除
     *
     * @mbg.generated
     */
    public void set是否删除(Boolean 是否删除) {
        this.是否删除 = 是否删除;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 用户信息表
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        用户信息 other = (用户信息) that;
        return (this.get编号() == null ? other.get编号() == null : this.get编号().equals(other.get编号()))
            && (this.get姓名() == null ? other.get姓名() == null : this.get姓名().equals(other.get姓名()))
            && (this.get性别() == null ? other.get性别() == null : this.get性别().equals(other.get性别()))
            && (this.get年龄() == null ? other.get年龄() == null : this.get年龄().equals(other.get年龄()))
            && (this.get生日() == null ? other.get生日() == null : this.get生日().equals(other.get生日()))
            && (this.get身份证号() == null ? other.get身份证号() == null : this.get身份证号().equals(other.get身份证号()))
            && (this.get创建时间() == null ? other.get创建时间() == null : this.get创建时间().equals(other.get创建时间()))
            && (this.get修改时间() == null ? other.get修改时间() == null : this.get修改时间().equals(other.get修改时间()))
            && (this.get是否删除() == null ? other.get是否删除() == null : this.get是否删除().equals(other.get是否删除()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 用户信息表
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((get编号() == null) ? 0 : get编号().hashCode());
        result = prime * result + ((get姓名() == null) ? 0 : get姓名().hashCode());
        result = prime * result + ((get性别() == null) ? 0 : get性别().hashCode());
        result = prime * result + ((get年龄() == null) ? 0 : get年龄().hashCode());
        result = prime * result + ((get生日() == null) ? 0 : get生日().hashCode());
        result = prime * result + ((get身份证号() == null) ? 0 : get身份证号().hashCode());
        result = prime * result + ((get创建时间() == null) ? 0 : get创建时间().hashCode());
        result = prime * result + ((get修改时间() == null) ? 0 : get修改时间().hashCode());
        result = prime * result + ((get是否删除() == null) ? 0 : get是否删除().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 用户信息表
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", 编号=").append(编号);
        sb.append(", 姓名=").append(姓名);
        sb.append(", 性别=").append(性别);
        sb.append(", 年龄=").append(年龄);
        sb.append(", 生日=").append(生日);
        sb.append(", 身份证号=").append(身份证号);
        sb.append(", 创建时间=").append(创建时间);
        sb.append(", 修改时间=").append(修改时间);
        sb.append(", 是否删除=").append(是否删除);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}