package cn.yurihentai.mapper;

import cn.yurihentai.bean.权限;
import cn.yurihentai.bean.权限Example;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface 权限Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 权限表
     *
     * @mbg.generated
     */
    long countByExample(权限Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 权限表
     *
     * @mbg.generated
     */
    int deleteByExample(权限Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 权限表
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long 编号);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 权限表
     *
     * @mbg.generated
     */
    int insert(权限 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 权限表
     *
     * @mbg.generated
     */
    int insertSelective(权限 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 权限表
     *
     * @mbg.generated
     */
    List<权限> selectByExample(权限Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 权限表
     *
     * @mbg.generated
     */
    权限 selectByPrimaryKey(Long 编号);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 权限表
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") 权限 record, @Param("example") 权限Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 权限表
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") 权限 record, @Param("example") 权限Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 权限表
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(权限 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 权限表
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(权限 record);

    //可以直接通过注解设置Sql语句，不必编写mapper.xml文件 @Select @Insert @Update @Delete
//    @Select("SELECT 编号, 名称, 编码, 创建时间, 修改时间" +
//            "FROM 权限表" +
//            "LEFT JOIN 角色_权限表" +
//            "ON 权限表.编号 = 角色_权限表.权限编号" +
//            "WHERE 角色_权限表.角色编号 = #{角色编号}" +
//            "AND 权限表.是否删除 = 0")
    List<权限> 通过角色编号查找权限(Long 角色编号);

}