package cn.yurihentai.mapper;

import cn.yurihentai.bean.用户;
import cn.yurihentai.bean.用户Example;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface 用户Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 用户表
     *
     * @mbg.generated
     */
    long countByExample(用户Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 用户表
     *
     * @mbg.generated
     */
    int deleteByExample(用户Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 用户表
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long 编号);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 用户表
     *
     * @mbg.generated
     */
    int insert(用户 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 用户表
     *
     * @mbg.generated
     */
    int insertSelective(用户 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 用户表
     *
     * @mbg.generated
     */
    List<用户> selectByExample(用户Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 用户表
     *
     * @mbg.generated
     */
    用户 selectByPrimaryKey(Long 编号);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 用户表
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") 用户 record, @Param("example") 用户Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 用户表
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") 用户 record, @Param("example") 用户Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 用户表
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(用户 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 用户表
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(用户 record);
}