package cn.yurihentai.springboot.mapper;

import org.apache.ibatis.annotations.Param;
import cn.yurihentai.springboot.bean.权限;
import cn.yurihentai.springboot.bean.权限Example;

import java.util.List;

public interface 权限Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 权限表
     *
     * @mbg.generated
     */
    long countByExample(权限Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 权限表
     *
     * @mbg.generated
     */
    int deleteByExample(权限Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 权限表
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long 编号);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 权限表
     *
     * @mbg.generated
     */
    int insert(权限 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 权限表
     *
     * @mbg.generated
     */
    int insertSelective(权限 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 权限表
     *
     * @mbg.generated
     */
    List<权限> selectByExample(权限Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 权限表
     *
     * @mbg.generated
     */
    权限 selectByPrimaryKey(Long 编号);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 权限表
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") 权限 record, @Param("example") 权限Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 权限表
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") 权限 record, @Param("example") 权限Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 权限表
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(权限 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 权限表
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(权限 record);

    List<权限> 通过角色编号查找权限(Long 角色编号);

}