spring:
  application:
    name: spring-cloud-provider-first

server:
  port: 6901

eureka:
  client:
    # 默认true  多节点时如果为false，将会导致无法启用ribbon负载均衡
    fetch-registry: true
    #指定将自己注册到哪个注册中心
    service-url:
      defaultZone: http://localhost:6969/eureka/
  instance:
    #是否用ip方式注册本服务
    prefer-ip-address: true
    # 指定在注册中心显示的名称（默认为主机名+服务名+端口号
    instance-id: cloud-provider-first