spring:
  application:
    name: spring-cloud-demo-server

server:
  port: 6971

eureka:
  instance:
    prefer-ip-address: true
    appname: spring-cloud-demo-server
  client:
    service-url:
      defaultZone: http://localhost:6969/eureka/

#开启Feign对Hystrix支持
# Hystrix主要功能：服务降级(fallback)  熔断(break)  限流(flowlimimt)
feign:
  circuitbreaker:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        # autoconfig，configprops，beans,dump,env,env/{name},mappings,metrics,metrics/{name},shutdown,trace
        include: health,info,hystrix.stream # 访问/actuator/hystrix.stream能看到不断更新的监控流

info:
  app-name: spring-cloud-demo-server
  company.addr: www.yurihentai.cn

# OpenFeign调用时有超时控制  默认如果超过1s没有得到响应 则会报错timeout
ribbon:
  ReadTimeout: 5000
  ConnectionTimeout: 5000
logging:
  level:
    # 指定feign要监控监控的接口  以及日志级别
    cn.yurihentai.springcloud.client.feign.*: debug
