server:
  port: 9000

spring:
  application:
    name: cloud-consul-provider
  cloud:
    consul: # consul注册中心地址
      host: localhost
      port: 8500
      discovery:
        # hostname: 127.0.0.1
        service-name: ${spring.application.name}